# Vectors

## About
- 1-D array of numbers
- Denoted in lowercase, italics,bold e.g ***x***
- Elements are arranged in an order, so you can access it like an index
    - Elements are scalars so they aren't bolded
- Vectors represents a point in space:
    - Vector of length two represents location in 2D matrix
    - Vector of length three represents location in 3D cube
    - Vector of length n represents location in n-dimensional tensor

## Vectors (Rank 1 Tensors) in Numpy


In [3]:
import numpy as np
x = np.array([25,2,5])
print(x)
print(len(x))
print(x.shape)
print(type(x))
print(x[0]) # We can access it like an array

[25  2  5]
3
(3,)
<class 'numpy.ndarray'>
25


### Vector Transposition

In [4]:
# Transposing a regular 1-D array has no effect

x_t = x.T
x_t

array([25,  2,  5])

In [5]:
x_t.shape # It has the same shape as the x above!

(3,)

In [6]:
y = np.array([[25,2,5]]) # Creating it but with a nested "matrix-style" bracket
y

array([[25,  2,  5]])

In [8]:
y.shape # It has 2 dimensions

(1, 3)

In [9]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [10]:
y_t.shape # Column vector so 3 rows and 1 column

(3, 1)

In [11]:
y_t.T # We can transpose a transposed vector to get our original vector

array([[25,  2,  5]])

In [12]:
y_t.T.shape

(1, 3)

### Zero vectors
Have no effect if added to another vector

In [13]:
z = np.zeros(3)
z

array([0., 0., 0.])

## Vectors in PyTorch

In [1]:
import torch
x_pt = torch.tensor([25,2,5])
x_pt

tensor([25,  2,  5])

In [2]:
x_pt.shape

torch.Size([3])