# Matrices

## Matrices (Rank 2 Tensors) in Numpy

In [2]:
import numpy as np
X = np.array([[25,2],[5,26],[3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X.shape

(3, 2)

In [4]:
X.size

6

In [7]:
print(X[:,0]) # Select left column
print(X[1,:]) # Select middle row
print(X[0:2, 0:2]) # Slicing by index

[25  5  3]
[ 5 26]
[[25  2]
 [ 5 26]]


## Matrice in PyTorch

In [2]:
import torch 

X_pt = torch.tensor([[25,2],[5,26],[3, 7]])
X_pt.shape

torch.Size([3, 2])

In [3]:
X_pt[1,:]

tensor([ 5, 26])

## High rank Tensors

In [4]:
images_pt = torch.zeros([32,28,28,3]) # 32 images, 28x28 resolution, 3 color channels
images_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.