# Common Tensor Operations

## Tensor Transposition

In [5]:
import numpy as np
x = np.array([[25,2],[5,26],[3,7]])
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [6]:
# Should return
# [25,5,3] [2,26,7]
x.T 

array([[25,  5,  3],
       [ 2, 26,  7]])

In [7]:
import torch
x_pt = torch.tensor([[25,2],[5,26],[3,7]])
x_pt.T 

tensor([[25,  5,  3],
        [ 2, 26,  7]])

## Basic Tensor Arithmetric

In [11]:
x*2 # We can muliply by scalar

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [10]:
x+2 # We can do addition with scalar

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

## Element-wise product (Hadamard Product)

In [16]:
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [13]:
a = x + 2
a

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [14]:
a + x

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [15]:
a * x 

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

## Reduction

In [17]:
x

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [19]:
x.sum()

68

In [20]:
torch.sum(x_pt)

tensor(68)

In [21]:
x.sum(axis=0) # Summing all rows

array([33, 35])

In [22]:
x.sum(axis=1) # Summing all columns

array([27, 31, 10])

In [23]:
torch.sum(x_pt,0) # Summing all rows in pytorch

tensor([33, 35])

Reduction isn't for summing alone. You can do max, min, mean and product

In [25]:
x.max()

26

In [26]:
torch.min(x_pt)

tensor(2)

In [27]:
x.mean(axis=1)

array([13.5, 15.5,  5. ])

In [29]:
torch.prod(x_pt,0)

tensor([375, 364])

## Dot Product

It can be annotated as x . y or x<sup>T</sup>y.

It is calculated by taking element-wise products and then sum reductively across the products to a scalar value.

In [36]:
x1 = np.array([25,2,5])

In [37]:
y = np.array([0,1,2])

In [38]:
sum = 0
for i in range(len(x1)):
    sum += x1[i] * y[i]
sum

12

In [40]:
np.dot(x1,y)

12