# Matrix Inversion

- Clever, convenient approach for solving linear equations. Alternative way to manually solving with substitution or elimination

- Matrix Inverse of X is **X<sup>-1</sup>**
- **X<sup>-1</sup>X=I<sub>n</sub>** 

- It can only be calculated if
    - Matrix isn't singular 
    - All columns are linearly independent 
    - The matrix is square i.e number of row = number of col

In [1]:
import numpy as np

X = np.array([[4,2],[-5,-3]])
X

array([[ 4,  2],
       [-5, -3]])

In [2]:
Xinv = np.linalg.inv(X)
Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [3]:
y = np.array([4,-7])
y

array([ 4, -7])

In [4]:
w = np.dot(Xinv,y)
w

array([-1.,  4.])

In [6]:
np.dot(X,w)

array([ 4., -7.])

## Matrix Inversion where there is no solution

In [12]:
X = np.array([[-4,1],[-8,2]]) # Singular matrix
X 

array([[-4,  1],
       [-8,  2]])

In [11]:
np.linalg.inv(X) #throws an error

LinAlgError: Singular matrix